import Head from 'next/head'
import { useEffect, useState } from 'react'
import Messages from '../components/MessageItem';

export interface Contact {
  uid: string
  name: string
  photoURL: string
  lastMessage: string
  lastMessageTime: number
}

export default function Home() {

  const [recipient, setRecipient] = useState<string>("")



 

  const [hide, setHide] = useState(true)

  // useEffect(() => {
  //   handleFirstCall();
  // }, [])

  const handleFirstCall = async () => {
    setHide(false)
  }

  

  return (
    <>
      <Head>
        <title>GPT Based support system</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {hide && <div className="text-3xl  bg-gradient-to-r from-cyan-500 to-blue-500 font-semibold font-pops h-[100vh] w-full overflow-hidden bg-[#1FAEFF5A] flex justify-center items-center gap-4">
        <span onClick={handleFirstCall} className='bg-[#FFF] px-10 py-5 rounded-full cursor-pointer hover:shadow'>
          Start chatting with GPT Bot
        </span>

      </div>}
      <div className={`h-[100vh] w-full overflow-hidden bg-gradient-to-r from-cyan-500 to-blue-500 flex justify-center items-center gap-4`}>
        <div className={`w-full drop-shadow-2xl flex justify-center items-center ${!hide ? 'transition  duration-1000 ease-in-out -translate-y-10' : 'absolute -bottom-100'}`}>
        <Messages recipient='123' />
        </div>
       
      </div>
    </>
  )
}
